

CREATE TABLE `label` (
  `label_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `label_name` varchar(50) NULL COMMENT '标签名',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`label_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8 COMMENT='题目标签表';
